trigger:
  branches:
    include:
      - master


pool:
  name: Default
  demands:
    - Agent.Name -equals nexa-belms


variables:

  buildConfiguration: 'Release'
  dotnetSdkVersion: '10.0.x'

  apiPublishDir: '$(Build.ArtifactStagingDirectory)\BELMS.Api'
  frontendPublishDir: '$(Build.ArtifactStagingDirectory)\BELMS.Frontend'

  apiDeployPath: 'C:\inetpub\wwwroot\BELMS.Api'
  frontendDeployPath: 'C:\inetpub\wwwroot\BELMS.Frontend'

  apiPoolName: 'BELMS.ApiPool'
  frontendPoolName: 'BELMS.FrontendPool'


steps:


- checkout: self
  clean: true



# Install .NET SDK

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'
    includePreviewVersions: true



# Restore

- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: 'restore'
    projects: 'BELMS.slnx'



# Build

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: 'BELMS.slnx'
    arguments: '--configuration $(buildConfiguration)'



# Publish API

- task: DotNetCoreCLI@2
  displayName: 'Publish BELMS.Api'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'BELMS.Api/BELMS.Api.csproj'
    arguments: '--configuration $(buildConfiguration) --output "$(apiPublishDir)"'
    zipAfterPublish: false



# Verify API Output

- powershell: |

    Write-Host "API Publish Files"

    Get-ChildItem "$(apiPublishDir)"


  displayName: 'Verify API Publish'



# Zip API

- task: ArchiveFiles@2
  displayName: 'Create BELMS.Api.zip'
  inputs:
    rootFolderOrFile: '$(apiPublishDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\BELMS.Api.zip'
    replaceExistingArchive: true




# Publish Frontend

- task: DotNetCoreCLI@2
  displayName: 'Publish BELMS.Frontend'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'BELMS.Frontend/BELMS.Frontend.csproj'
    arguments: '--configuration $(buildConfiguration) --output "$(frontendPublishDir)"'
    zipAfterPublish: false



# Zip Frontend

- task: ArchiveFiles@2
  displayName: 'Create BELMS.Frontend.zip'
  inputs:
    rootFolderOrFile: '$(frontendPublishDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\BELMS.Frontend.zip'
    replaceExistingArchive: true




# Create IIS Pools

- powershell: |

    Import-Module WebAdministration


    if (!(Test-Path "IIS:\AppPools\$(apiPoolName)")) {

        New-WebAppPool -Name "$(apiPoolName)"

        Set-ItemProperty `
        "IIS:\AppPools\$(apiPoolName)" `
        -Name managedRuntimeVersion `
        -Value ""

    }


    if (!(Test-Path "IIS:\AppPools\$(frontendPoolName)")) {

        New-WebAppPool -Name "$(frontendPoolName)"

        Set-ItemProperty `
        "IIS:\AppPools\$(frontendPoolName)" `
        -Name managedRuntimeVersion `
        -Value ""

    }


  displayName: 'Create IIS Application Pools'




# Deploy API

- powershell: |

    Import-Module WebAdministration


    Write-Host "Stopping API Pool"


    Stop-WebAppPool "$(apiPoolName)"


    Write-Host "Stopping dotnet processes"


    Get-Process dotnet -ErrorAction SilentlyContinue |
    Stop-Process -Force


    Start-Sleep -Seconds 5



    if (!(Test-Path "$(apiDeployPath)")) {

        New-Item `
        -ItemType Directory `
        -Path "$(apiDeployPath)" | Out-Null

    }



    Write-Host "Cleaning API"


    Remove-Item "$(apiDeployPath)\*" `
    -Recurse `
    -Force `
    -ErrorAction SilentlyContinue



    Write-Host "Copy API"


    robocopy `
    "$(apiPublishDir)" `
    "$(apiDeployPath)" `
    /MIR `
    /R:3 `
    /W:5



    if ($LASTEXITCODE -gt 7) {

        throw "API Copy Failed"

    }



    Start-WebAppPool "$(apiPoolName)"


    Write-Host "API Deployment Completed"


  displayName: 'Deploy BELMS.Api'




# Deploy Frontend

- powershell: |

    Import-Module WebAdministration



    Write-Host "Stopping Frontend Pool"


    Stop-WebAppPool "$(frontendPoolName)"



    if (!(Test-Path "$(frontendDeployPath)")) {

        New-Item `
        -ItemType Directory `
        -Path "$(frontendDeployPath)" | Out-Null

    }



    Write-Host "Cleaning Frontend"


    Remove-Item "$(frontendDeployPath)\*" `
    -Recurse `
    -Force `
    -ErrorAction SilentlyContinue



    Write-Host "Copy Frontend"



    robocopy `
    "$(frontendPublishDir)" `
    "$(frontendDeployPath)" `
    /MIR `
    /R:3 `
    /W:5



    if ($LASTEXITCODE -gt 7) {

        throw "Frontend Copy Failed"

    }



    Start-WebAppPool "$(frontendPoolName)"


    Write-Host "Frontend Deployment Completed"


  displayName: 'Deploy BELMS.Frontend'




# Publish Artifact

- task: PublishBuildArtifacts@1
  displayName: 'Publish Release Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'