trigger:
  branches:
    include:
      - master


pool:
  name: Default
  demands:
    - Agent.Name -equals nexa-belms


variables:

  buildConfiguration: 'Release'
  dotnetSdkVersion: '10.0.x'

  apiPublishDir: '$(Build.ArtifactStagingDirectory)\BELMS.Api'
  frontendPublishDir: '$(Build.ArtifactStagingDirectory)\BELMS.Frontend'

  apiDeployPath: 'C:\inetpub\wwwroot\BELMS.Api'
  frontendDeployPath: 'C:\inetpub\wwwroot\BELMS.Frontend'

  apiPoolName: 'BELMS.ApiPool'
  frontendPoolName: 'BELMS.FrontendPool'


steps:


# Checkout

- checkout: self
  clean: true



# Install .NET SDK

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'
    includePreviewVersions: true



# Restore

- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: restore
    projects: 'BELMS.slnx'



# Build

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: build
    projects: 'BELMS.slnx'
    arguments: '--configuration $(buildConfiguration)'



# Publish API

- task: DotNetCoreCLI@2
  displayName: 'Publish BELMS.Api'
  inputs:

    command: publish

    publishWebProjects: false

    projects: 'BELMS.Api/BELMS.Api.csproj'

    arguments: >
      --configuration $(buildConfiguration)
      --output "$(apiPublishDir)"

    zipAfterPublish: false



# Check API output

- powershell: |

    Write-Host "API Files"

    Get-ChildItem "$(apiPublishDir)" -Recurse


  displayName: 'Check API Publish'



# Zip API

- task: ArchiveFiles@2
  displayName: 'Zip BELMS.Api'

  inputs:

    rootFolderOrFile: '$(apiPublishDir)'

    includeRootFolder: false

    archiveType: zip

    archiveFile: '$(Build.ArtifactStagingDirectory)\BELMS.Api.zip'

    replaceExistingArchive: true





# Publish Frontend

- task: DotNetCoreCLI@2

  displayName: 'Publish BELMS.Frontend'

  inputs:

    command: publish

    publishWebProjects: false

    projects: 'BELMS.Frontend/BELMS.Frontend.csproj'

    arguments: >
      --configuration $(buildConfiguration)
      --output "$(frontendPublishDir)"

    zipAfterPublish: false





# Zip Frontend

- task: ArchiveFiles@2

  displayName: 'Zip BELMS.Frontend'

  inputs:

    rootFolderOrFile: '$(frontendPublishDir)'

    includeRootFolder: false

    archiveType: zip

    archiveFile: '$(Build.ArtifactStagingDirectory)\BELMS.Frontend.zip'

    replaceExistingArchive: true





# Create IIS Application Pools

- powershell: |

    Import-Module WebAdministration



    # API Pool

    if (!(Test-Path "IIS:\AppPools\$(apiPoolName)")) {


        New-WebAppPool `
        -Name "$(apiPoolName)"


        Set-ItemProperty `
        "IIS:\AppPools\$(apiPoolName)" `
        -Name managedRuntimeVersion `
        -Value ""


        Write-Host "Created API Pool"

    }



    # Frontend Pool


    if (!(Test-Path "IIS:\AppPools\$(frontendPoolName)")) {


        New-WebAppPool `
        -Name "$(frontendPoolName)"


        Set-ItemProperty `
        "IIS:\AppPools\$(frontendPoolName)" `
        -Name managedRuntimeVersion `
        -Value ""


        Write-Host "Created Frontend Pool"

    }


  displayName: 'Create IIS Pools'





# Deploy API

- powershell: |

    Import-Module WebAdministration



    Write-Host "Stopping API Pool"


    if(Test-Path "IIS:\AppPools\$(apiPoolName)"){

        Stop-WebAppPool "$(apiPoolName)"

    }



    if(!(Test-Path "$(apiDeployPath)")){

        New-Item `
        -ItemType Directory `
        -Path "$(apiDeployPath)"

    }



    Write-Host "Cleaning API folder"


    Remove-Item "$(apiDeployPath)\*" `
    -Recurse `
    -Force `
    -ErrorAction SilentlyContinue



    Write-Host "Copying API files"



    Copy-Item `
    "$(apiPublishDir)\*" `
    "$(apiDeployPath)" `
    -Recurse `
    -Force




    Start-WebAppPool "$(apiPoolName)"



    Write-Host "API Deployment Completed"


  displayName: 'Deploy BELMS.Api'





# Deploy Frontend


- powershell: |

    Import-Module WebAdministration



    Write-Host "Stopping Frontend Pool"



    if(Test-Path "IIS:\AppPools\$(frontendPoolName)"){

        Stop-WebAppPool "$(frontendPoolName)"

    }



    if(!(Test-Path "$(frontendDeployPath)")){


        New-Item `
        -ItemType Directory `
        -Path "$(frontendDeployPath)"

    }



    Remove-Item "$(frontendDeployPath)\*" `
    -Recurse `
    -Force `
    -ErrorAction SilentlyContinue




    Copy-Item `
    "$(frontendPublishDir)\*" `
    "$(frontendDeployPath)" `
    -Recurse `
    -Force




    Start-WebAppPool "$(frontendPoolName)"



    Write-Host "Frontend Deployment Completed"



  displayName: 'Deploy BELMS.Frontend'





# Publish Artifact

- task: PublishBuildArtifacts@1

  displayName: 'Publish Release Artifact'

  inputs:

    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

    ArtifactName: 'drop'

    publishLocation: 'Container'